source 'https://rubygems.org'

# Project requirements
gem 'rake'

# DataBase
gem 'pg'
gem 'sequel'

# Padrino Stable Gem
gem 'padrino', '0.12.5'

# Generate JSON API
gem 'rabl'
gem 'oj'

# Possword secure
gem 'bcrypt'

# JSON Web Token
gem 'jwt'

# CORS
gem 'rack-cors', require: 'rack/cors'

group :development do
  # Code style
  gem 'rubocop', require: false

  # Better errors
  gem 'better_errors'
  gem 'binding_of_caller'
end

group :test do
  gem 'rspec'
  gem 'rack-test', require: 'rack/test'
end
