source 'https://rubygems.org'

# Project requirements
gem 'rake'

# Component requirements
gem 'slim'

# DataBase
gem 'pg'
gem 'sequel'

# Test requirements
gem 'rspec', :group => 'test'
gem 'rack-test', :require => 'rack/test', :group => 'test'

# Padrino Stable Gem
gem 'padrino', '0.12.5'

# generate JSON API
gem 'rabl'
gem 'oj'
